parameters:
    alpha_vantage.api.host: https://www.alphavantage.co
    alpha_vantage.api.key: '%env(ALPHA_VANTAGE_API_KEY)%'
    share.redis.url: '%env(REDIS_URL)%'
    share.redis.ttl: 600 # 10 Minutes cache

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\SharesService:
        bind:
            $sharesClient: '@App\Share\AlphaVantage\ApiClient'

    App\Share\AlphaVantage\ApiClient:
        arguments: ['@share.alpha_vantage.http_client', '%alpha_vantage.api.key%', '@App\Share\Cache\RedisCacheAdapter']

    App\Share\Cache\RedisCacheAdapter:
        arguments: ['@share.redis_client', '%share.redis.ttl%']

    share.redis_client:
        class: Predis\Client
        arguments: ['%share.redis.url%']

    share.alpha_vantage.http_client:
        class: GuzzleHttp\Client
        arguments:
            -   base_uri: '%alpha_vantage.api.host%'
                http_errors: false
