version: '3.4'

services:
    ls-stock-app-api:
        container_name: stock-app-api-fpm
        build:
            context: ./backend/
            dockerfile: Dockerfile
            args:
                - DEV=true
        restart: always
        environment:
            PORT: 8000
        links:
            - ls-stock-api-redis
        volumes:
            - './backend/:/var/www'
        ports:
            - 8000:8000

    ls-stock-api-redis:
        container_name: redis
        image: redis
        ports:
            - '6379:6389'

    ls-stock-app-ui:
        container_name: stock-app-ui
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        environment:
            REACT_APP_STOCK_API_HOST: 'http://127.0.0.1:8000'
        command: ['serve', '-s', 'build', '-l', '5000']
        restart: always
        links:
            - ls-stock-app-api
        volumes:
            - './frontend/:/app'
        ports:
            - 5000:5000
